### ISSUE TITLE
Feedback for Personal-Task (문승현 튜터)

### ISSUE THREAD

**Issue by bewisesh91** [APD-Kim/Personal-Task#1]
안녕하세요 :) 첫 개인 과제 제출 고생하셨습니다! 
아래 체크 리스트는 기본 구현 사항 체크에 대한 것입니다!

개인 과제 기본 구현 사항 체크
[1] jQuery 라이브러리 사용없이 순수 바닐라 자바스크립트 사용하기 👍 💯
[2] TMDB 오픈 API를 이용하여 인기영화 데이터 가져오기 👍 💯
[3] 영화정보 카드 리스트 UI 구현 👍 💯
[4] 영화 검색 UI 구현 👍 💯
[5] 하기 기재된 Javascript 문법 요소를 이용하여 구현 👍 💯

기본 구현 사항 모두 잘 수행하신 것 같아요.
이외에 피드백드리고 싶은 점을 아래와 같이 적어보았습니다.

1. 더 보기 기능
- 영화를 더보고 싶다면 더 보기를 클릭하도록 하는 기능을 추가하셨는데 잘하셨습니다.
- 주어진 것(기대하는 것) 이상을 해내는 것 역시 개발자로서 좋은 역량이라고 생각합니다.

2. 영화 정보 조회 기능
- 지금은 영화를 클릭했을 때 ID만 노출되는 것 같아요.
- 영화에 대한 세부 정보를 확인할 수 있는 기능을 완벽하게 구현하면 더 좋을 것 같습니다.

3. 폴더 분리
- 현재 코드를 Node.js 기반으로 동작하도록 작성하셨는데, 폴더 구조가 살짝 어색한 것 같아요.
- 기능별로 모아놓은 것인지, commons라고 하면 일반적으로 공통적으로 사용하는 기능이 포함되어야할 것 같은데 지금은 사실 index.mjs에 해당 내용들이 다있어도 이상하지 않을 것 같아요.
- 하지만, 이렇게 분리를 시도하는 것은 좋은 시도이오니 앞으로는 내가 어떤 기능과 어떤 기능을 구분하고 싶고, 어떤 것을 모아두고 싶은지 고민해보면 좋을 것 같습니다.

**Comment by APD-Kim** [comment]
감사합니다! 피드백 주신 부분은 고민해서 한번 변경해보겠습니다!
